// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw9OVf_sP0MXX6HA6asLPYtRc0FiQnWWo',
    appId: '1:494901573890:web:d61ac254272288c2b92a1b',
    messagingSenderId: '494901573890',
    projectId: 'bookkeeping-1c097',
    authDomain: 'bookkeeping-1c097.firebaseapp.com',
    storageBucket: 'bookkeeping-1c097.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0TGp8zppujSpyQKXxK6w6gqjjYUhGUQ8',
    appId: '1:494901573890:android:70d35fa68c3b38ebb92a1b',
    messagingSenderId: '494901573890',
    projectId: 'bookkeeping-1c097',
    storageBucket: 'bookkeeping-1c097.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaBXBGMDOvyQen21rEo4NTCbg0msHongY',
    appId: '1:494901573890:ios:5dc385dfaeca61d3b92a1b',
    messagingSenderId: '494901573890',
    projectId: 'bookkeeping-1c097',
    storageBucket: 'bookkeeping-1c097.appspot.com',
    iosBundleId: 'cz.muni.fi.bookKeeping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaBXBGMDOvyQen21rEo4NTCbg0msHongY',
    appId: '1:494901573890:ios:e84d963aeebeb6d3b92a1b',
    messagingSenderId: '494901573890',
    projectId: 'bookkeeping-1c097',
    storageBucket: 'bookkeeping-1c097.appspot.com',
    iosBundleId: 'cz.muni.fi.bookKeeping.RunnerTests',
  );
}
